import { type NextPage } from "next";
import Head from "next/head";

import { api } from "@/utils/api";
import { SignIn, SignInButton, useUser } from "@clerk/nextjs";

import CreatePostWizard from "@/components/CreatePostWizard";
import PostView from "@/components/PostView";
import LoadingSpinner from "@/components/LoadingSpinner";

const Feed = () => {
  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <LoadingSpinner />;
  if (!data) return <div>Something went wrong</div>;

  return (
    <div className="flex flex-col">
      {data?.map(({ post, author }) => (
        <PostView post={post} author={author} key={post.id} />
      ))}
    </div>
  );
};

const Home: NextPage = () => {
  const { isSignedIn, isLoaded } = useUser();

  api.posts.getAll.useQuery();

  if (!isLoaded) return <LoadingSpinner />;

  return (
    <>
      <Head>
        <title>Chirp T3 App | Feed</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {isSignedIn ? <CreatePostWizard /> : <SignInButton />}
          </div>

          <Feed />
        </div>

        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      </main>
    </>
  );
};

export default Home;
