import { type NextPage } from "next";
import Head from "next/head";

import { api } from "@/utils/api";
import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  const { user, isSignedIn } = useUser();

  const { data } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {!!user ? (
          <div className="flex flex-col items-center justify-center">
            <h1 className="text-4xl font-bold text-white">
              Hello {user?.fullName}!
            </h1>
            {isSignedIn && <SignOutButton />}

            {data?.map((post) => (
              <div key={post.id} className="text-white">
                {post.content}
              </div>
            ))}
          </div>
        ) : (
          <SignInButton />
        )}

        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      </main>
    </>
  );
};

export default Home;
