import { type NextPage } from "next";
import Head from "next/head";
import PageLayout from "@/components/PageLayout";

const SinglePostPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Chirp T3 App | Post</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLayout>Post Page</PageLayout>
    </>
  );
};

export default SinglePostPage;
