import { type NextPage } from "next";
import Head from "next/head";

import { SignIn } from "@clerk/nextjs";

const SinglePostPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Chirp T3 App | Post</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          Post Page
        </div>

        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      </main>
    </>
  );
};

export default SinglePostPage;
